site_name: 'Midwest Data Science'
site_description: 'Data Science Resources for the Midwest'
site_author: 'Shawn Hermans'
site_url: 'https://github.com/midwest-datascience/'

# Navigation
nav:
  - Home: 'index.md'

# Copyright
copyright: 'Copyright &copy; Shawn Hermans'

# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'red'
    accent: 'red'
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - toc.integrate

# Plugins
plugins:
  - search

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - def_list
  - footnotes
  - md_in_html
  - meta
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - toc:
      permalink: true

extra_javascript:
  - assets/js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
